### ISSUE TITLE
Install failed on linux 

### ISSUE THREAD

**Issue by thammegowda** [manalishah/mitie-resources#1]
![screenshot from 2016-04-22 21 08 45](https://cloud.githubusercontent.com/assets/1865964/14759206/99bb0f00-08ce-11e6-8ae1-82c3b9af2073.png)

Please fix if-then-else syntax on line 38 : https://github.com/manalishah/mitie-resources/blob/master/install.sh#L38

**Comment by manalishah** [comment]
@thammegowda fixed
